name: Copybara Migration Workflow

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  migrate:
    runs-on: ubuntu-latest  # Using Ubuntu as the base image

    steps:
    - name: Checkout the source repository
      uses: actions/checkout@v2
      with:
        repository: "kahlon1005/copybara-source"  # Source repository
        ref: "master"  # Branch to use

    - name: Checkout the destination repository
      uses: actions/checkout@v2
      with:
        repository: "kahlon1005/copybara-target"  # Destination repository
        ref: "master"  # Branch to use
        path: destination  # This will checkout to the 'destination' folder

    - name: Install Java 23 (Eclipse Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: '23'  # Specify the Java version as 23
        distribution: 'temurin'  # Eclipse Temurin distribution for Java 23

    - name: Download copybara_deploy.jar
      run: |
        # Download copybara_deploy.jar from the specified release
        curl -L https://github.com/google/copybara/releases/download/v20250224/copybara_deploy.jar -o $HOME/copybara_deploy.jar

    - name: Run Copybara Migration
      run: |
        # Run the Copybara migration using the downloaded copybara_deploy.jar
        java -jar $HOME/copybara_deploy.jar migrate --config $GITHUB_WORKSPACE/copy.bara.sky  # Ensure the correct path to your configuration file
